version: "3.8"

services:
  service-app-fastify:
    image: service-app-fastify
    #set name container
    container_name: service-app-fastify
    #set domain
    # domainname: jarcreator.com
    networks:
      - code-overlay
    env_file:
      - ./development.env
    deploy:
      replicas: 1
      resources:
        limits: 
          cpus: '0.7'
          memory: 2048M
        reservations:
          cpus: '0.5'
          memory: 1024M
      restart_policy: 
        condition: on-failure

networks:
  code-overlay:
    external: true
